`authorization-server:
  public-base-url`: https://localhost:8443
server:
  ssl:
    key-store-type: PKCS12
    key-store: "classpath:keystore/localhost.p12"
    key-store-password: Geheim123!
    key-alias: localhost
  port: 8443
security:
  require-ssl: true
logging.level.org.springframework.security.web.FilterChainProxy: DEBUG